"""remove resume file path

Revision ID: 66fe40dd7112
Revises: 425500b27cae
Create Date: 2026-08-12 23:18:09.433868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fe40dd7112'
down_revision: Union[str, Sequence[str], None] = '425500b27cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
